apiVersion: v1
kind: ConfigMap
metadata:
  name: wsusscn2-api-config
  namespace: wsusscn2-api
data:
  PG_HOST: "postgres"
  PG_PORT: "5432"
  PG_DATABASE: "wsus"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: "http://minio:9000"
  CAB_SYNC_INTERVAL: "1d12h"
  GROUP_STRATEGY: "Year-OS"
  API_PORT: "5000"
  CORS_ORIGINS: "http://localhost:3000,http://ui:80"
  LOG_LEVEL: "Information"
