apiVersion: v1
kind: Secret
metadata:
  name: wsusscn2-api-secrets
  namespace: wsusscn2-api
type: Opaque
data:
  # These are base64 encoded placeholders - replace with real values in production
  PG_USER: cG9zdGdyZXM=  # postgres
  PG_PASSWORD: Y2hhbmdlX21lX2luX3Byb2R1Y3Rpb24=  # change_me_in_production
  REDIS_PASSWORD: ""
  MINIO_ACCESS_KEY: YWRtaW4=  # admin
  MINIO_SECRET_KEY: Y2hhbmdlX21lX2luX3Byb2R1Y3Rpb24=  # change_me_in_production
  UI_DEFAULT_USER: YWRtaW4=  # admin
  UI_DEFAULT_PASSWORD: Y2hhbmdlX21lX2luX3Byb2R1Y3Rpb24=  # change_me_in_production
